[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["openweathermap_apr27_test_1"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/ManualTrigger","Category/Integration"]
  name = "openweathermap_apr27_test_1"
  org = "lakshansivagnanasothy"
  version = "3.1.0"

